language: go

go:
 - 1.5.4
 - 1.6.4
 - 1.7.4
 - 1.8rc2

# Get deps, build, test, and ensure the code is gofmt'ed.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
